# Generated by Django 5.0.6 on 2024-06-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='id del producto')),
                ('nombreProducto', models.CharField(max_length=30, verbose_name='nombre del producto')),
                ('descripcion', models.CharField(max_length=50, verbose_name='descripcion del producto')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='core/img/')),
                ('precio', models.IntegerField(verbose_name='precio del producto')),
                ('stock', models.IntegerField(verbose_name='stock del producto')),
                ('categoria', models.CharField(max_length=20, verbose_name='categoria del producto')),
            ],
        ),
    ]
